env_name: BreakoutNoFrameskip-v4
action_dimention: 4
state_dimention: 4
seed: 0

DQN:
  env_name: BreakoutNoFrameskip-v4
  action_dimention: 4
  state_dimention: 4
  capacity: 10000
  batch_size: 256
  seed: 0
  start_timesteps: 25000
  eval_freq: 5000
  max_timesteps: 1000000
  discount: 0.99
  lr: 0.001
  epsilon: 1
  epsilon_decay: 0.995
  target_update_step: 100
  algo: DQN