env_name: VideoPinball-ramNoFrameskip-v4
action_dimention: 9
state_dimention: 128
seed: 0

DQN:
  env_name: VideoPinball-ramNoFrameskip-v4
  action_dimention: 9
  state_dimention: 128
  capacity: 100000
  batch_size: 256
  seed: 0
  start_timesteps: 25000
  eval_freq: 5000
  max_timesteps: 1000000
  discount: 0.99
  lr: 0.001
  epsilon: 1
  epsilon_decay: 0.995
  target_update_step: 100
  algo: DQN